---
name: 002 - Apply Terraform AWS

on:
  workflow_dispatch:

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: us-east-1

jobs:
  packer_build:
    defaults:
      run:
        working-directory: ./terraform
    name: Packer Terraform AWS
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

     # Terra
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
         cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

    - name: Terraform Init
      run: terraform init

    - name: Terraform Format Fix
      run: terraform fmt .

    - name: Terraform Format
      run: terraform fmt -check
  
    - name: Terraform Apply
      run: terraform apply -auto-approve    
